import random

def Hangman1wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                       __________╟──╢__________                  ")
    print("    ║                      /                        \                 ")
    print("    ║                     |                          |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |_____________|     |                ")
    print("    ║                      \____/|             |\___/                 ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            \______/\_____/                      ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")
def Hangman2wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                       __________╟──╢__________                  ")
    print("    ║                      /                        \                 ")
    print("    ║                     |                          |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |_____________|     |                ")
    print("    ║                      \____/|             |\___/                 ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                   |      |                      ")
    print("    ║                                    \_____/                      ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")
def Hangman3wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                       __________╟──╢__________                  ")
    print("    ║                      /                        \                 ")
    print("    ║                     |                          |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |_____________|     |                ")
    print("    ║                      \____/|             |\___/                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")
def Hangman4wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                       __________╟──╢__________                  ")
    print("    ║                      /                        \                ")
    print("    ║                     |                                           ")
    print("    ║                     |      |             |                      ")
    print("    ║                     |      |             |                      ")
    print("    ║                     |      |             |                      ")
    print("    ║                     |      |             |                      ")
    print("    ║                     |      |             |                      ")
    print("    ║                     |      |             |                      ")
    print("    ║                     |      |_____________|                      ")
    print("    ║                      \____/|                                    ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")

def Hangman5wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                       __________╟──╢__________                  ")
    print("    ║                      /____               ____ \                 ")
    print("    ║                            |             |                      ")
    print("    ║                            |             |                      ")
    print("    ║                            |             |                      ")
    print("    ║                            |             |                      ")
    print("    ║                            |             |                      ")
    print("    ║                            |             |                      ")
    print("    ║                            |             |                      ")
    print("    ║                            |_____________|                      ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")

def Hangman6wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")
def Hangman7wrong():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     X   X   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("    ║                                                                 ")
    print("════╩═════════════════════════════════════════════════════════════════")
    print("                                     YOU DIED                         ")

def Animals():
    Animals = ["JACKRABBIT", "AMBERJACK", "CARJACK", "APPLEJACK", "BLACKSHAFT", "JACKSHAFT"]
    RandAnimal = random.choice(Animals)
    thinkofitlater = len(RandAnimal)
    var = " _"
    PositiveFeedback = 0
    newvar = thinkofitlater
    Guessesthatarewrong = 0
    while newvar > 0 and PositiveFeedback != thinkofitlater:
        var = var + " _"
        newvar -= 1
    #add print thing
        Guess = input("                  ¿What is your guess?")
        if Guess in RandAnimal:
            print("                      Correct!")
            count = 0
            while count < thinkofitlater:
                if Guess == RandAnimal [count]:
                    print("YOUR LETTER IS IN POSITION" + str(count))
                    PositiveFeedback += 1
                count +=1
        else:
            Guessesthatarewrong += 1
            print(Guessesthatarewrong)
            if(Guessesthatarewrong == 1):
                Hangman1wrong()
            if(Guessesthatarewrong == 2):
                Hangman2wrong()
            if(Guessesthatarewrong == 3):
                Hangman3wrong()
            if(Guessesthatarewrong == 4):
                Hangman4wrong()
            if(Guessesthatarewrong == 5):
                Hangman5wrong()
            if(Guessesthatarewrong == 6):
                Hangman6wrong()
            if(Guessesthatarewrong == 7):
                print("Died u")
                break


        if PositiveFeedback == thinkofitlater:
            print("NYAN CAT LATER")


print("                                                                      ")
print("                      ________________________                        ")
print("                         WELCOME TO HANGMAN                           ")
print("                      ~~~~~~~~~~~~~~~~~~~~~~~~                        ")
print("                              David Han                               ")
print("                                                                      ")
print("                        ¡¡CHOSE YOUR MODE!!                           ")
print("                      ¿Easy, Medium(Unavalible), or Hard(Unavalible)?                         ")
Mode = input("                              ")

if(Mode == "Easy"):
    print("                  ¡¡CHOOSE YOUR CATEGORY!!                            ")
    print("        ¿Animals, Foods(Unavalible), Colors(Unavalible), Logos(Unavalible), Occupations(Unavalible)?                  ")
    Category = input("                     ")



if Category == "Animals":
    Animals()



def FullHangman():
    print("                                                                      ")
    print("    ╔══════════════════════════════════╤══                            ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                                  │                              ")
    print("    ║                              _________                          ")
    print("    ║                            /           \                        ")
    print("    ║                           |     ○   ○   |                       ")
    print("    ║                           |             |                       ")
    print("    ║                           |             |                       ")
    print("    ║                            \    ────   /                        ")
    print("    ║                              ─────────                          ")
    print("    ║                       __________╟──╢__________                  ")
    print("    ║                      /                        \                 ")
    print("    ║                     |                          |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |             |     |                ")
    print("    ║                     |      |_____________|     |                ")
    print("    ║                      \____/|             |\___/                 ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            |      |      |                      ")
    print("    ║                            \______/\_____/                      ")
    print("    ║                      ╔═════════════════════════╗                ")
    print("    ║                      ║                         ║                ")
    print("    ║                      ║                         ║                ")
    print("    ║                      ║                         ║                ")
    print("    ║                      ║                         ║                ")
    print("════╩══════════════════════╩═════════════════════════╩════════════════")
    print("                                                                      ")
    print("                               _ _ _ _ _ _ _ _ _ _                    ")
    print("                                                                      ")
    print("                                CHOSE YOUR LETTER                     ")
    print("                                                                      ")
